### ISSUE TITLE
Crash on OpenJ9-based JVMs

### ISSUE THREAD

**Issue by xtrm-en** [Polyfrost/OneConfig#198]
### Bug description

OneConfig seems to crash on OpenJ9-based JVMs, such as `IBM Semuru`.

From the stacktrace, we can think that this is due to the EventBus implementation using Lambda Metafactories to generate invoker code not being valid on J9 standards compared to HotSpot.

```
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
    at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.ExceptionInInitializerError
    at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:184)
    at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:173)
    at cc.polyfrost.oneconfig.internal.OneConfig.init(OneConfig.java:135)
    at net.minecraft.resource.DefaultResourcePack.handler$zzi000$onStart(DefaultResourcePack.java:555)
    at net.minecraft.resource.DefaultResourcePack.<init>(DefaultResourcePack.java:21)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:276)
    at net.minecraft.client.main.Main.main(Main.java:124)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
    ... 3 more
Caused by: java.lang.invoke.LambdaConversionException: Invalid caller: cc.polyfrost.oneconfig.utils.gui.GuiUtils
    at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.<init>(AbstractValidatingLambdaMetafactory.java:120)
    at java.base/java.lang.invoke.InnerClassLambdaMetafactory.<init>(InnerClassLambdaMetafactory.java:172)
    at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:323)
    at cc.polyfrost.oneconfig.libs.eventbus.invokers.LMFInvoker.setup(LMFInvoker.java:19)
    at cc.polyfrost.oneconfig.libs.eventbus.EventBus.register(eventbus.kt:69)
    at cc.polyfrost.oneconfig.events.EventManager.register(EventManager.java:69)
    at cc.polyfrost.oneconfig.utils.gui.GuiUtils.<clinit>(GuiUtils.java:54)
    ... 9 more
```

### Steps to reproduce

1. Use an OpenJ9-based JVM
2. Launch OneConfig (only tested in development environment)
3. Crash

### Expected behavior

OneConfig should be able to load properly on any type of JVM and should not rely on implementation-specific behavior.

### Anything else?

To fix the issue would require replacing the current EventBus library with another that doesn't use Lambda Metafactories as its invoker method. 

The current one I'm suggesting is [Shyrogan/Post](https://github.com/Shyrogan/Post), which uses runtime class generation for listener construction via ASM.

**Comment by xtrm-en** [comment]
Don't close, this is just an excuse to switch EventBus at some point cuz faster blazing performance uwu

**Comment by Wyvest** [comment]
Not fixing this, I don't see a lot of reasons why

**Comment by xtrm-en** [comment]
> Don't close, this is just an excuse to switch EventBus at some point cuz faster blazing performance uwu

bruh

**Comment by dynpatch** [comment]
Note for anyone looking at this: This will be fixed with the release of OneConfig v1
