### ISSUE TITLE
OneConfig not saving settings

### ISSUE THREAD

**Issue by DylanBruner** [Polyfrost/OneConfig#320]
### Category

Backend

### Bug description

I've been using the oneconfig demo mod as a base for my mod for a while now. But recently i'm getting this error over and over and it's not saving the users settings.

```
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: java.lang.IllegalArgumentException: class java.text.Format$Field declares multiple JSON fields named serialVersionUID
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:122)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.Gson.getAdapter(Gson.java:356)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.Gson.getAdapter(Gson.java:356)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ArrayTypeAdapter$1.create(ArrayTypeAdapter.java:48)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.Gson.getAdapter(Gson.java:356)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.Gson.getAdapter(Gson.java:356)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.Gson.getAdapter(Gson.java:356)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.Gson.getAdapter(Gson.java:356)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.Gson.getAdapter(Gson.java:356)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.Gson.getAdapter(Gson.java:356)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.Gson.getAdapter(Gson.java:356)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.Gson.getAdapter(Gson.java:356)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.Gson.getAdapter(Gson.java:356)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.Gson.getAdapter(Gson.java:356)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.Gson.getAdapter(Gson.java:356)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.Gson.toJson(Gson.java:585)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.Gson.toJson(Gson.java:572)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.Gson.toJson(Gson.java:527)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at com.google.gson.Gson.toJson(Gson.java:507)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at cc.polyfrost.oneconfig.config.Config.save(Config.java:167)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at cc.polyfrost.oneconfig.internal.config.core.ConfigCore.saveAll(ConfigCore.java:45)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[10:12:28] [pool-7-thread-1/INFO] (STDERR) [cc.polyfrost.oneconfig.config.Config:save:169]: 	at java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce

mod list: OneConfig, my mod
loader: forge
version: 1.8.9

clone the example mod and make changes to the config.

**Comment by nextdayy** [comment]
this is most probably caused by you attempting to save an object which is not directly serializable. Could you share your config class?

**Comment by nextdayy** [comment]
okay, thank you. most likely, the issue is caused by your HUD class. For any field you do not want saved in that class, you need to either add the `transient` modifier or add the `@Exclude` annotation to the field.

this is caused by default behaviour we plan to change, which is that it will attempt to saved any field unless told otherwise. In future versions, only fields explicitly marked will be saved.
